# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
    - image: cimg/node:14.15.1
    steps:
      - checkout
      - run: ls -lah
      - run: /app/test
      - run: echo "this is the build job"

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build_deploy:
    # Run the welcome/run job in its own container
    jobs:
      - build
