version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: artikusnc/testedev:tagname
    docker:
      - image: cimg/node:14.15.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t devops:1.2 .
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main